### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by jackyshaw2017** [harlanc/rsfu#2]
error: this arithmetic operation will overflow
   --> rsfu\src\sfu\helpers.rs:158:36
    |
158 |         let sec = self.ntp_time >> (32 * 1000000000);
    |                                    ^^^^^^^^^^^^^^^^^ attempt to compute `32_i32 * 1000000000_i32`, which would overflow
    |
    = note: `#[deny(arithmetic_overflow)]` on by default

error: could not compile `rsfu` (lib) due to previous error

**Comment by harlanc** [comment]
Thanks for your report, please pull the latest code and try again.
